# Generated by Django 3.2.8 on 2021-10-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsession',
            name='text',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
