# Generated by Django 3.2.8 on 2021-10-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
