# Generated by Django 3.2.5 on 2021-11-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_commentsession_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title2',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
