# Generated by Django 3.2.8 on 2021-11-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('create',)},
        ),
    ]
