# Generated by Django 3.2.8 on 2021-11-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsession',
            old_name='blog',
            new_name='blogs',
        ),
    ]
