# Generated by Django 3.2.8 on 2021-11-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_blog_commentsession_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsession',
            old_name='blogs',
            new_name='idBlog',
        ),
    ]
