# Generated by Django 3.2.8 on 2021-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_commentsession_idblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsession',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
