# Generated by Django 3.2.8 on 2021-11-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_commentsession_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsession',
            name='idBlog',
        ),
    ]
