# Generated by Django 3.2.8 on 2021-11-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_commentsession_idblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsession',
            old_name='idBlog',
            new_name='blogs',
        ),
    ]
