# Generated by Django 3.2.8 on 2021-12-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_idblog_commentsession_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
